[tool.ruff]

target-version = "py39"

extend-select = [
  "B",
  "C",
  "I",
]

exclude = [
	"extensions",
	"extensions-disabled",
]

ignore = [
	"E501", # Line too long
	"E731", # Do not assign a `lambda` expression, use a `def`
	
	"I001", # Import block is un-sorted or un-formatted
	"C901", # Function is too complex
	"C408", # Rewrite as a literal
	"B007", # Loop control variable not used within loop body

]


[tool.ruff.per-file-ignores]
"webui.py" = ["E402"]  # Module level import not at top of file
