[tool.ruff]

target-version = "py310"

exclude = [
	"extensions",
	"extensions-disabled",
]

ignore = [
	"E501", # Line too long
	"E731", # Do not assign a `lambda` expression, use a `def`
]


[tool.ruff.per-file-ignores]
"webui.py" = ["E402"]  # Module level import not at top of file
